apiVersion: apps/v1
kind: Deployment
metadata:
  name: $name;format="normalize"$-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: $name;format="normalize"$
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: $name;format="normalize"$
        branch: {{ git_branch }}
    spec:
      containers:
        - name: $name;format="normalize"$-container
          image: ruchira088/$name;format="normalize"$:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: $name;format="normalize"$-data-config-map
            - secretRef:
                name: $name;format="normalize"$-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: $name;format="normalize"$-file-config-map

