apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $name;format="normalize"$-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: $name;format="normalize"$-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: $name;format="normalize"$-service
                port:
                  name: http4s-port