apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $name;format="normalize"$-ingress
  namespace: $name;format="normalize"$-{{ git_branch }}
spec:
  tls:
    - secretName: $name;format="normalize"$-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              serviceName: $name;format="normalize"$-service
              servicePort: http4s-port