apiVersion: v1
kind: Secret
metadata:
  name: $name;format="normalize"$-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}