apiVersion: v1
kind: Service
metadata:
  name: $name;format="normalize"$-service
  namespace: {{ namespace }}
spec:
  selector:
    app: $name;format="normalize"$
    branch: {{ git_branch }}
  ports:
    - name: http4s-port
      port: 8080