- name: Encrypt value
  command: ./lib-sodium/index.js -k {{ public_key }} -s {{ lookup('aws_ssm', "{{ aws_ssm_path }}", region='ap-southeast-2') }}
  register: encrypted_output

- name: Add secret to GitHub repository
  uri:
    url: https://api.github.com/repos/ruchira088/{{ repo_name }}/actions/secrets/{{ secret_name }}
    headers:
      Accept: application/vnd.github+json
      Authorization: token {{ access_token }}
    method: PUT
    body_format: json
    body:
      encrypted_value: "{{ encrypted_output.stdout }}"
      key_id: "{{ public_key_id }}"
    status_code:
      - 201
      - 204