- name: Print start message
  debug:
    msg: Started building $name;format="normalize"$

- name: Clean and build sbt project
  shell: cd ../ && sbt clean Universal/packageZipTarball

- name: Gather git information
  import_tasks: git-info.yml

- name: Build Docker image
  shell: |
    docker build \
      -t ghcr.io/ruchira088/$name;format="normalize"$:{{ git_branch }} \
      -t ghcr.io/ruchira088/$name;format="normalize"$:{{ git_branch }}-{{ git_commit }} \
      -f docker/Dockerfile \
      ../target/universal/
  when: not publish

- name: Build and publish Docker image
  when: publish
  block:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ghcr.io/ruchira088/$name;format="normalize"$:{{ git_branch }} \
          -t ghcr.io/ruchira088/$name;format="normalize"$:{{ git_branch }}-{{ git_commit }} \
          -f docker/Dockerfile \
          ../target/universal/

- name: Print finish message
  debug:
    msg: Completed building $name;format="normalize"$