- name: Check if git repository
  command: git status
  register: git_status
  ignore_errors: yes

- name: Gather git information
  when: not git_status.failed
  block:
    - name: Get the git commit tag
      command: git rev-parse --short HEAD
      register: git_commit_output

    - name: Get the git branch name
      shell: git rev-parse --abbrev-ref HEAD | tr "[:upper:]" "[:lower:]" | tr " /" "-"
      register: git_branch_output

    - set_fact:
        git_commit: "{{ git_commit_output.stdout }}"
        git_branch: "{{ git_branch_output.stdout }}"

- name: Populate placeholder git values
  when: git_status.failed
  set_fact:
    git_commit: commit
    git_branch: main