- name: Create output directory
  file:
    path: k8s-output
    state: directory

- name: Create K8s config file
  copy:
    dest: k8s-output/kubeconfig
    content: "{{ lookup('aws_ssm', aws_ssm_k8s_config_path, region='ap-southeast-2', aws_profile='personal') }}"