- name: Create output directories
  block:
    - name: Delete existing output directory
      file:
        path: k8s-output
        state: absent

    - name: Create output directory
      file:
        path: k8s-output
        state: directory

- name: Gather git information
  import_tasks: tasks/git-info.yml

- name: Set config values and secrets
  import_tasks: tasks/configs-and-secrets.yml

- name: Render K8s resource files
  template:
    src: "{{ item }}"
    dest: k8s-output/{{ item | basename }}
  with_fileglob:
    - k8s/*.yaml