- name: Gather git information
  import_tasks: git-info.yml

- name: Login to Docker Hub
  command: docker login -u {{ docker_username }} -p {{ docker_password }}
  vars:
    docker_username: "{{ lookup('aws_ssm', '/docker-hub/credentials/username', region='ap-southeast-2', aws_profile='personal') }}"
    docker_password: "{{ lookup('aws_ssm', '/docker-hub/credentials/password', region='ap-southeast-2', aws_profile='personal') }}"

- name: Publish Docker image
  shell: |
    docker tag $name;format="normalize"$:{{ git_commit }} ruchira088/$name;format="normalize"$:{{ git_commit }} && \
    docker push ruchira088/$name;format="normalize"$:{{ git_commit }}