version: 2

jobs:
  build:
    docker:
      - image: openjdk:8
    working_directory: ~/project
    steps:
      - run:
          name: Install sbt
          command: |
            apt-get update && \
                apt-get install apt-transport-https bc ca-certificates software-properties-common -y

            echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
                apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
                apt-get update && \
                apt-get install sbt -y
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Create a new sbt project from the g8 template
          command: sbt g8
  test:
    docker:
      - image: openjdk:8
    working_dir: ~/project/target/g8
    steps:
      - run:
          name: Run the test suite of the newly created project
          command: sbt clean test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2"
            - "~/.sbt"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build