version: 2.1

alias:
  - &install-sbt
    name: Install sbt
    command: |
      echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list && \
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
      sudo apt-get update && \
      sudo apt-get install sbt -y

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: *install-sbt
      - checkout
      - restore_cache:
          key: sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run:
          name: Create a new sbt project from the g8 template
          command: sbt g8
      - run:
          name: Run the test suite of the newly created project
          command: cd target/g8 && sbt clean test
      - save_cache:
          key: sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
          paths:
            - ~/.sbt
            - ~/.cache/coursier
