version: 2.1

aliases:
  - &install-ansible
    name: Install Ansible
    command: |
      sudo apt update && \
      sudo apt install python3-pip -y && \
      pip3 install boto3 botocore openshift ansible

jobs:
  build-ci-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run: *install-ansible
      - checkout
      - run:
          name: Build and publish Docker CI image
          command: ansible-playbook playbooks/build-and-publish-docker-ci.yml

  build-and-test:
    docker:
      - image: ruchira088/docker-ci:http4s-seed
    steps:
      - checkout
      - restore_cache: &dependency-cache-keys
          key: sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
      - run: &sbt_template_project
          name: Create a new sbt project from the g8 template
          command: sbt g8
      - run:
          name: Run the test suite of the newly created project
          command: cd target/g8 && sbt clean test
      - save_cache:
          key: sbt-cache-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
          paths:
            - ~/.sbt
            - ~/.cache/coursier

  build-and-publish-docker-image:
    docker:
      - image: ruchira088/docker-ci:http4s-seed
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache: *dependency-cache-keys
      - run: *sbt_template_project
      - run:
          name: Build and publish Docker image
          command: ansible-playbook target/g8/playbooks/build-and-publish-docker-image.yml

  deploy-to-k8s:
    docker:
      - image: ruchira088/docker-ci:http4s-seed
    steps:
      - checkout
      - restore_cache: *dependency-cache-keys
      - run: *sbt_template_project
      - run:
          name: Deploy to home K8s server
          command: ansible-playbook target/g8/playbooks/k8s-deploy.yml

orbs:
  slack: circleci/slack@3

workflows:
  version: 2

  http4s-seed:
    jobs:
      - build-and-test:
          post-steps:
            - slack/status

      - build-and-publish-docker-image:
          context: aws-credentials
          requires:
            - build-and-test
          post-steps:
            - slack/status

      - deploy-to-k8s:
          context: aws-credentials
          requires:
            - build-and-publish-docker-image
          post-steps:
            - slack/status

  docker-ci:
    jobs:
      - build-ci-image:
          context: aws-credentials
          post-steps:
            - slack/status
    triggers:
      - schedule:
          cron: "0 4 1,15 * *"
          filters:
            branches:
              only:
                - master


