FROM openjdk:8-jdk-slim

WORKDIR /opt

ADD target/universal/$name;format="normalize"$-*.tgz .

RUN mv $name;format="normalize"$-* $name;format="normalize"$

CMD [ "/opt/$name;format="normalize"$/bin/$name;format="normalize"$" ]
