FROM openjdk:21-jdk-slim

RUN apt-get update && \
    apt-get install apt-transport-https bc ca-certificates software-properties-common -y

# Install sbt
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import && \
    sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg && \
    sudo apt-get update && \
    sudo apt-get install sbt

WORKDIR /opt/$name;format="normalize"$

COPY . .

EXPOSE 8080 5005

ENTRYPOINT ["sbt", "-jvm-debug", "5005"]

CMD ["run"]
