---
- hosts: localhost
  connection: local

  tasks:
    - name: Build Docker image
      import_tasks: tasks/build-docker-prod.yml

    - name: Publish Docker image
      import_tasks: tasks/publish-docker-image.yml
