---
- hosts: localhost
  connection: local

  tasks:
    - name: Remove Video Downloader API Docker images
      shell: docker images | grep "$name;format="normalize"$" | awk '{print \$3}' | xargs docker rmi -f