FROM openjdk:11-jre-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/$name;format="normalize"$

ADD $name;format="normalize"$-*.tgz .

EXPOSE 8000

CMD [ "/opt/$name;format="normalize"$/bin/$name;format="normalize"$" ]
