FROM eclipse-temurin:25-jre

LABEL org.opencontainers.image.source=https://github.com/ruchira088/$name;format="normalize"$

WORKDIR /opt/$name;format="normalize"$

ADD $name;format="normalize"$-*.tgz .

EXPOSE 8080

CMD [ "/opt/$name;format="normalize"$/bin/$name;format="normalize"$" ]
