FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/$name;format="normalize"$

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/$name;format="normalize"$

ADD $name;format="normalize"$-*.tgz .

EXPOSE 8080

CMD [ "/opt/$name;format="normalize"$/bin/$name;format="normalize"$" ]
