name: Http4s Seed Build Pipeline

on: [push, pull_request]

jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}
            http4s-seed-${{ runner.os }}

      - name: Create new sbt project from g8 template
        run: sbt g8

      - name: Execute test suite
        run: cd target/g8 && sbt clean test

      - name: Send successful Slack message
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :white_check_mark: *SUCCESS*
            *${{ github.repository }}*
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send failure Slack message
        if: failure()
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :x: *FAILURE*
            *${{ github.repository }}*
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}