name: http4s scala3 seed pipeline

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    name: Compile & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}
            http4s-seed-${{ runner.os }}

      - name: Create new sbt project from g8 template
        run: sbt g8

      - name: Execute test suite
        run: cd target/g8 && sbt clean test

      - name: Send failure Slack message
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :x: *FAILURE*
            *${{ github.repository }}*
            *Job:* compile-and-test
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs:
      - compile-and-test

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            http4s-seed-${{ runner.os }}-${{ hashFiles('**/build.properties') }}
            http4s-seed-${{ runner.os }}

      - name: Create new sbt project from g8 template
        run: sbt g8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: backend-deploy
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Build and publish Docker image
        run: ansible-playbook target/g8/playbooks/build-and-publish-docker-image.yml

      - name: Send failure Slack message
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :x: *FAILURE*
            *${{ github.repository }}*
            *Job:* build-and-publish-docker-image
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy-to-k8s:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    needs:
      - publish-docker-image

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/Dependencies.scala') }}
          path: |
            ~/.sbt
            ~/.cache/coursier
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/build.properties') }}-${{ hashFiles('**/plugins.sbt') }}
            ${{ runner.os }}-${{ hashFiles('**/build.properties') }}
            ${{ runner.os }}

      - name: Create new sbt project from g8 template
        run: sbt g8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-session-name: backend-deploy
          role-to-assume: "arn:aws:iam::365562660444:role/github_iam_role"

      - name: Deploy to K8s server
        run: ansible-playbook target/g8/playbooks/k8s-deploy.yml

      - name: Send failure Slack message
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :x: *FAILURE*
            *${{ github.repository }}*
            *Job:* deploy-to-k8s
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send successful Slack message
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: C02HYP398KS
          slack-message: |
            :white_check_mark: *SUCCESS*
            *${{ github.repository }}*
            *Branch:* ${{ github.ref }}
            *Commit:* `${{ github.sha }}`
            *Last Commit Message:* ${{ github.event.head_commit.message }}
            *URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
